// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.example.grpcjava.protogen;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   */
  String getValue();
  /**
   * <code>string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
